main/apps/portfolios/urls.py
from django.conf.urls import url, include
from . import views           # This line is new!
urlpatterns = [
    url(r'^', views.index, name='index'),
    url(r'^create', views.create, name='create'),
    url(r'^(?P<id>\d+)$', views.show, name='show'),
    url(r'^(?P<id>\d+)/delete$', views.delete, name='delete'),
    ]

main/apps/userloginreg/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$',views.register, name='create'),
    url(r'login$',views.login, name='login'),
    url(r'landingpage/$', views.landingpage, name='success'),
    url(r'logout$',views.logout, name='logout')
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^port/', include('apps.port.urls', namespace='portfolio')),
    url(r'^portfolios/', include('apps.portfolios.urls', namespace='portfolios')),
    url(r'^$', include('apps.userloginreg.urls')),
    url(r'^home/', include('apps.userloginreg.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
]

main/apps/portfolios/models.py
from __future__ import unicode_literals

from django.db import models
from ..userloginreg.models import User

# class PortfolioManager(models.Manager):
    # def portfolioValidator(portfolio):
    #     portfolioRow = Portfolio.objects.get(id = portfolio.id)
    #     portfolioRow.title = portfolio.title
    #     try:
    #         portfolioRow.save()
    #         return True
    #     except:
    #         return False
# Create your models here.
class Portfolio(models.Model):
    title = models.CharField(max_length = 70, null = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User, related_name = "portfolios")
    # objects = PortfolioManager()

main/apps/portfolios/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from .models import Portfolio
# Create your views here.
def index(request):
    print "portfolios index page"
    if not 'user_id' in request.session:
		return redirect('home:index')
    # response = "Portfolios"
    # return HttpResponse(response)
    context = { 'portfolios': Portfolio.objects.all().order_by('portfolio__title')}
    return render(request,'portfolios/index.html') # , context
def create(request):
    print "1 - trying to create..."

    if request.method == 'POST':
        print "2 - trying to create..."
        curr_user = User.get(id = int(request.session['user_id']))

        Portfolio.objects.create(title = request.POST['title'], user = curr_user)
    return redirect('home:success')

def show(request,id):
    print 'portfolios show page'
    return redirect('portfolios:index')
def delete(request):
    return redirect('portfolios:index')

main/apps/portfolios/templates/portfolios/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Maintain Courses">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='col-md-10'>
        <h1>Portfolios</h1>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:success' %}">Dashboard</a>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:logout' %}">Logout</a>
      </div>
    </div>
    <form action='{% url 'portfolios:create' %}' method='POST'>
      {% csrf_token %}
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='title'>Title:</label>
        <input class='col-md-7' name='title'/>
      </div>
      <div class='row'>
        <div class='col-md-offset-3 col-md-3'>
          <button class='btn btn-primary btn-block' type='submit' name='create'>Create</button>
        </div>
      </div>
      </div>
    </form>
    <div id='window'>
      <table>
        <div class='row'>
          <thead>
            <tr>
              <td class='col-md-2'><strong>Portfolio</strong></td>
\              <td class='col-md-2'><strong>Created At</strong></td>
              <td class='col-md-2'><strong>Last Updated</strong></td>
              <td class='col-md-1'><strong>Action(s)</strong></td>
            </tr>
          </thead>
        </div>
        {% for row in portfolios %}
        <div class='row'>
          <tr>
            <td class='col-md-2'>{{row.title}}</td>
            <td class='col-md-2'>{{row.created_at}}</td>
            <td class='col-md-2'>{{row.updated_at}}</td>
            <td class='col-md-1'><a href="{% url 'portfolios:show' id=row.id %}">Edit</a></td>
            <td class='col-md-1'><a href="{% url 'portfolios:delete' id=row.id %}">Delete</a></td>
          </tr>
        </div>
        {% endfor %}
            </table>
    </div>
  </div>
</body>
</html>

main/apps/portfolios/templates/portfolios/show.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Maintain Courses">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    <h1>Portfolio show page</h1>
  </div>
</body>
</html>